-- Add user tag fields
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "tagText" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "tagColor" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "tagStyle" TEXT;
