services:
  - type: web
    name: nexo-messenger
    env: docker
    region: frankfurt
    plan: starter
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /api/health
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: DATABASE_URL
        value: postgresql://neondb_owner:npg_HtISpB5j2how@ep-flat-haze-aijugpbg-pooler.c-4.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
      - key: REDIS_URL
        value: redis://default:YmDlMjlsmXYjoFH13l0SWHPf0C23tXau@redis-18158.c14.us-east-1-2.ec2.cloud.redislabs.com:18158
      - key: REDIS_SESSION_URL
        value: redis://default:x69uHtIDnVVRf371e3HYOb4BZNfBjNHS@redis-13102.c17.us-east-1-4.ec2.cloud.redislabs.com:13102
      - key: JWT_SECRET
        sync: false
      - key: ENCRYPTION_KEY
        sync: false
      - key: CORS_ORIGINS
        value: "*"
      - key: STORAGE_MODE
        value: telegram
      - key: MAX_REGISTRATIONS_PER_IP
        value: "10"
    disk:
      name: uploads
      mountPath: /app/apps/server/uploads
      sizeGB: 1
